const AnaJR =
  {'ArticunoANAPromo.jpg' : require('../../../resources/images/cards/ArticunoANAPromo.jpg'),
'FlyingPikachuANAPromo98.jpg' : require('../../../resources/images/cards/FlyingPikachuANAPromo98.jpg'),
'FlyingPikachuANAPromo99.jpg' : require('../../../resources/images/cards/FlyingPikachuANAPromo99.jpg'),
'MeowthWizardsPromo10.jpg' : require('../../../resources/images/cards/MeowthWizardsPromo10.jpg'),
'MoltresANAPromo.jpg' : require('../../../resources/images/cards/MoltresANAPromo.jpg'),
'promo-4-010.jpg' : require('../../../resources/images/cards/promo-4-010.jpg'),
'promo-4-013.jpg' : require('../../../resources/images/cards/promo-4-013.jpg'),
'promo-4-024.jpg' : require('../../../resources/images/cards/promo-4-024.jpg'),
'promo-5-003.jpg' : require('../../../resources/images/cards/promo-5-003.jpg'),
'promo-6-015.jpg' : require('../../../resources/images/cards/promo-6-015.jpg'),
'SurfingPikachuJRStampRallyPromo.jpg' : require('../../../resources/images/cards/SurfingPikachuJRStampRallyPromo.jpg'),
'TogepiANAPromo.jpg' : require('../../../resources/images/cards/TogepiANAPromo.jpg'),
'ZapdosANAPromo.jpg' : require('../../../resources/images/cards/ZapdosANAPromo.jpg'),};
export default AnaJR
