const AquaHalfDeck2 =
 {'TeamAquaSealeoEXTeamMagmavsTeamAqua31.jpg' : require('../../../resources/images/cards/TeamAquaSealeoEXTeamMagmavsTeamAqua31.jpg'),
'RaikouexEXTeamMagmavsTeamAqua92.jpg' : require('../../../resources/images/cards/RaikouexEXTeamMagmavsTeamAqua92.jpg'),
'TeamAquaSphealEXTeamMagmavsTeamAqua56.jpg' : require('../../../resources/images/cards/TeamAquaSphealEXTeamMagmavsTeamAqua56.jpg'),
'TeamAquaConspiratorEXTeamMagmavsTeamAqua77.jpg' : require('../../../resources/images/cards/TeamAquaConspiratorEXTeamMagmavsTeamAqua77.jpg'),
'TeamAquaPoochyenaEXTeamMagmavsTeamAqua54.jpg' : require('../../../resources/images/cards/TeamAquaPoochyenaEXTeamMagmavsTeamAqua54.jpg'),
'TeamAquaElectrikeEXTeamMagmavsTeamAqua53.jpg' : require('../../../resources/images/cards/TeamAquaElectrikeEXTeamMagmavsTeamAqua53.jpg'),
'DarknessEnergyEXRubySapphire93.jpg' : require('../../../resources/images/cards/DarknessEnergyEXRubySapphire93.jpg'),
'TeamAquaWalreinEXTeamMagmavsTeamAqua6.jpg' : require('../../../resources/images/cards/TeamAquaWalreinEXTeamMagmavsTeamAqua6.jpg'),
'TeamAquaMightyenaEXTeamMagmavsTeamAqua30.jpg' : require('../../../resources/images/cards/TeamAquaMightyenaEXTeamMagmavsTeamAqua30.jpg'),
'WaterEnergyEXRubySapphire106.jpg' : require('../../../resources/images/cards/WaterEnergyEXRubySapphire106.jpg'),
'TeamAquaTechnicalMachine01EXTeamMagmavsTeamAqua79.jpg' : require('../../../resources/images/cards/TeamAquaTechnicalMachine01EXTeamMagmavsTeamAqua79.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'TeamAquaCorphishEXTeamMagmavsTeamAqua50.jpg' : require('../../../resources/images/cards/TeamAquaCorphishEXTeamMagmavsTeamAqua50.jpg'),
'LightningEnergyEXRubySapphire109.jpg' : require('../../../resources/images/cards/LightningEnergyEXRubySapphire109.jpg'),
'TeamAquaSchemerEXTeamMagmavsTeamAqua69.jpg' : require('../../../resources/images/cards/TeamAquaSchemerEXTeamMagmavsTeamAqua69.jpg'),
'DoubleFullHealEXSandstorm86.jpg' : require('../../../resources/images/cards/DoubleFullHealEXSandstorm86.jpg'),
'TeamAquaBeltEXTeamMagmavsTeamAqua76.jpg' : require('../../../resources/images/cards/TeamAquaBeltEXTeamMagmavsTeamAqua76.jpg'),
'TeamAquaCrawdauntEXTeamMagmavsTeamAqua14.jpg' : require('../../../resources/images/cards/TeamAquaCrawdauntEXTeamMagmavsTeamAqua14.jpg'),
'TeamAquaCorphishEXTeamMagmavsTeamAqua51.jpg' : require('../../../resources/images/cards/TeamAquaCorphishEXTeamMagmavsTeamAqua51.jpg'),
'TeamAquaElectrikeEXTeamMagmavsTeamAqua52.jpg' : require('../../../resources/images/cards/TeamAquaElectrikeEXTeamMagmavsTeamAqua52.jpg'),
'TeamAquaManectricEXTeamMagmavsTeamAqua29.jpg' : require('../../../resources/images/cards/TeamAquaManectricEXTeamMagmavsTeamAqua29.jpg')};

export default AquaHalfDeck2