const CoroCoroBestPhotoContest =
  {'SquirtleSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/SquirtleSnapBestPhotoContest.jpg'),
'PoliwagSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/PoliwagSnapBestPhotoContest.jpg'),
'GyaradosSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/GyaradosSnapBestPhotoContest.jpg'),
'BulbasaurSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/BulbasaurSnapBestPhotoContest.jpg'),
'PikachuSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/PikachuSnapBestPhotoContest.jpg'),
'ArticunoSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/ArticunoSnapBestPhotoContest.jpg'),
'ChanseySnapBestPhotoContest.jpg' : require('../../../resources/images/cards/ChanseySnapBestPhotoContest.jpg'),
'MagikarpSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/MagikarpSnapBestPhotoContest.jpg'),
'KoffingSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/KoffingSnapBestPhotoContest.jpg'),
'CharmanderSnapBestPhotoContest.jpg' : require('../../../resources/images/cards/CharmanderSnapBestPhotoContest.jpg')};
export default CoroCoroBestPhotoContest
