const EarthsGroudonexConstructedStarterDeck =
 {'FightingEnergyEXRubySapphire105.jpg' : require('../../../resources/images/cards/FightingEnergyEXRubySapphire105.jpg'),
'BillMaintenanceExpedition137.jpg' : require('../../../resources/images/cards/BillMaintenanceExpedition137.jpg'),
'GrassEnergyEXRubySapphire104.jpg' : require('../../../resources/images/cards/GrassEnergyEXRubySapphire104.jpg'),
'SwampertEXCrystalGuardians27.jpg' : require('../../../resources/images/cards/SwampertEXCrystalGuardians27.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'CharmanderEXCrystalGuardians49.jpg' : require('../../../resources/images/cards/CharmanderEXCrystalGuardians49.jpg'),
'IvysaurEXCrystalGuardians34.jpg' : require('../../../resources/images/cards/IvysaurEXCrystalGuardians34.jpg'),
'MudkipEXCrystalGuardians57.jpg' : require('../../../resources/images/cards/MudkipEXCrystalGuardians57.jpg'),
'EnergySearchExpedition153.jpg' : require('../../../resources/images/cards/EnergySearchExpedition153.jpg'),
'PokeNavEXRubySapphire88.jpg' : require('../../../resources/images/cards/PokeNavEXRubySapphire88.jpg'),
'DualBallExpedition139.jpg' : require('../../../resources/images/cards/DualBallExpedition139.jpg'),
'CelioNetworkEXFireRedLeafGreen88.jpg' : require('../../../resources/images/cards/CelioNetworkEXFireRedLeafGreen88.jpg'),
'MarshtompEXCrystalGuardians38.jpg' : require('../../../resources/images/cards/MarshtompEXCrystalGuardians38.jpg'),
'GroudonexEXCrystalGuardians93.jpg' : require('../../../resources/images/cards/GroudonexEXCrystalGuardians93.jpg'),
'LightningEnergyEXRubySapphire109.jpg' : require('../../../resources/images/cards/LightningEnergyEXRubySapphire109.jpg'),
'MultiEnergyEXSandstorm93.jpg' : require('../../../resources/images/cards/MultiEnergyEXSandstorm93.jpg'),
'DoubleFullHealEXSandstorm86.jpg' : require('../../../resources/images/cards/DoubleFullHealEXSandstorm86.jpg'),
'BulbasaurEXCrystalGuardians45.jpg' : require('../../../resources/images/cards/BulbasaurEXCrystalGuardians45.jpg'),
'CharmeleonEXCrystalGuardians30.jpg' : require('../../../resources/images/cards/CharmeleonEXCrystalGuardians30.jpg')};

export default EarthsGroudonexConstructedStarterDeck