const Gym =
  {'BlaineGrowlitheCoroCoroPromo.jpg' : require('../../../resources/images/cards/BlaineGrowlitheCoroCoroPromo.jpg'),
'BrockMankeyCoroCoroPromo.jpg' : require('../../../resources/images/cards/BrockMankeyCoroCoroPromo.jpg'),
'BrockOnixCoroCoroPromo.jpg' : require('../../../resources/images/cards/BrockOnixCoroCoroPromo.jpg'),
'ErikaBulbasaurCoroCoroPromo.jpg' : require('../../../resources/images/cards/ErikaBulbasaurCoroCoroPromo.jpg'),
'ErikaDratiniCoroCoroPromo.jpg' : require('../../../resources/images/cards/ErikaDratiniCoroCoroPromo.jpg'),
'GiovanniNidokingCoroCoroPromo.jpg' : require('../../../resources/images/cards/GiovanniNidokingCoroCoroPromo.jpg'),
'KogaNinjaGymCoroCoroPromo.jpg' : require('../../../resources/images/cards/KogaNinjaGymCoroCoroPromo.jpg'),
'LtSurgeElectabuzzCoroCoroPromo.jpg' : require('../../../resources/images/cards/LtSurgeElectabuzzCoroCoroPromo.jpg'),
'LtSurgeJolteonCoroCoroPromo.jpg' : require('../../../resources/images/cards/LtSurgeJolteonCoroCoroPromo.jpg'),
'MistyStaryuCoroCoroPromo.jpg' : require('../../../resources/images/cards/MistyStaryuCoroCoroPromo.jpg'),
'MistyTentacoolCoroCoroPromo.jpg' : require('../../../resources/images/cards/MistyTentacoolCoroCoroPromo.jpg'),
'promo-3-022.jpg' : require('../../../resources/images/cards/promo-3-022.jpg')};
export default Gym
