const Gym =
  {'LtSurgeJolteonCoroCoroPromo.jpg' : require('../../../resources/images/cards/LtSurgeJolteonCoroCoroPromo.jpg'),
'BrockOnixCoroCoroPromo.jpg' : require('../../../resources/images/cards/BrockOnixCoroCoroPromo.jpg'),
'GiovanniNidokingCoroCoroPromo.jpg' : require('../../../resources/images/cards/GiovanniNidokingCoroCoroPromo.jpg'),
'MistyStaryuCoroCoroPromo.jpg' : require('../../../resources/images/cards/MistyStaryuCoroCoroPromo.jpg'),
'ErikaBulbasaurCoroCoroPromo.jpg' : require('../../../resources/images/cards/ErikaBulbasaurCoroCoroPromo.jpg'),
'BlaineGrowlitheCoroCoroPromo.jpg' : require('../../../resources/images/cards/BlaineGrowlitheCoroCoroPromo.jpg'),
'KogaNinjaGymCoroCoroPromo.jpg' : require('../../../resources/images/cards/KogaNinjaGymCoroCoroPromo.jpg'),
'BrockMankeyCoroCoroPromo.jpg' : require('../../../resources/images/cards/BrockMankeyCoroCoroPromo.jpg'),
'ErikaDratiniCoroCoroPromo.jpg' : require('../../../resources/images/cards/ErikaDratiniCoroCoroPromo.jpg'),
'LtSurgeElectabuzzCoroCoroPromo.jpg' : require('../../../resources/images/cards/LtSurgeElectabuzzCoroCoroPromo.jpg'),
'SabrinaAbraWizardsPromo19.jpg' : require('../../../resources/images/cards/SabrinaAbraWizardsPromo19.jpg'),
'MistyTentacoolCoroCoroPromo.jpg' : require('../../../resources/images/cards/MistyTentacoolCoroCoroPromo.jpg')};
export default Gym
