const Jumbo =
  {'CrystalTowerEnteiCoroCoroPromo.jpg' : require('../../../resources/images/cards/CrystalTowerEnteiCoroCoroPromo.jpg'),
'LawrenceIIICoroCoropromo.jpg' : require('../../../resources/images/cards/LawrenceIIICoroCoropromo.jpg'),
'MewtwoStrikesBackCoroCoroPromo.jpg' : require('../../../resources/images/cards/MewtwoStrikesBackCoroCoroPromo.jpg'),
'NewCenturyPresentFanClubPromo.jpg' : require('../../../resources/images/cards/NewCenturyPresentFanClubPromo.jpg'),
'NewYearPresentFanClubPromo.jpg' : require('../../../resources/images/cards/NewYearPresentFanClubPromo.jpg'),
'PichuPikachuCoroCoroPromo.jpg' : require('../../../resources/images/cards/PichuPikachuCoroCoroPromo.jpg'),
'PikachuJigglypuffClefairyCoroCoroPromo.jpg' : require('../../../resources/images/cards/PikachuJigglypuffClefairyCoroCoroPromo.jpg'),
'PikachuSummerVacationCoroCoroPromo.jpg' : require('../../../resources/images/cards/PikachuSummerVacationCoroCoroPromo.jpg'),
'PokemonPlazaCoroCoroPromo.jpg' : require('../../../resources/images/cards/PokemonPlazaCoroCoroPromo.jpg'),
'PokemonValleyCoroCoroPromo.jpg' : require('../../../resources/images/cards/PokemonValleyCoroCoroPromo.jpg'),
'promo-3-006.jpg' : require('../../../resources/images/cards/promo-3-006.jpg'),
'promo-5-011.jpg' : require('../../../resources/images/cards/promo-5-011.jpg'),
'ShadowLugiaNintendoWorldPromo.jpg' : require('../../../resources/images/cards/ShadowLugiaNintendoWorldPromo.jpg'),
'TropicalPresentEarly1999Promo.jpg' : require('../../../resources/images/cards/TropicalPresentEarly1999Promo.jpg'),
'TropicalPresentSummer1999Promo.jpg' : require('../../../resources/images/cards/TropicalPresentSummer1999Promo.jpg'),
'TropicalPresentSummer2001Promo.jpg' : require('../../../resources/images/cards/TropicalPresentSummer2001Promo.jpg')};
export default Jumbo
