const MagmaHalfDeck1 =
 {'FightingEnergyEXRubySapphire105.jpg' : require('../../../resources/images/cards/FightingEnergyEXRubySapphire105.jpg'),
'EnteiexEXTeamMagmavsTeamAqua91.jpg' : require('../../../resources/images/cards/EnteiexEXTeamMagmavsTeamAqua91.jpg'),
'TeamMagmaBaltoyEXTeamMagmavsTeamAqua61.jpg' : require('../../../resources/images/cards/TeamMagmaBaltoyEXTeamMagmavsTeamAqua61.jpg'),
'TeamMagmaConspiratorEXTeamMagmavsTeamAqua82.jpg' : require('../../../resources/images/cards/TeamMagmaConspiratorEXTeamMagmavsTeamAqua82.jpg'),
'TeamMagmaTechnicalMachine01EXTeamMagmavsTeamAqua84.jpg' : require('../../../resources/images/cards/TeamMagmaTechnicalMachine01EXTeamMagmavsTeamAqua84.jpg'),
'DarknessEnergyEXRubySapphire93.jpg' : require('../../../resources/images/cards/DarknessEnergyEXRubySapphire93.jpg'),
'TeamMagmaHoundoomEXTeamMagmavsTeamAqua34.jpg' : require('../../../resources/images/cards/TeamMagmaHoundoomEXTeamMagmavsTeamAqua34.jpg'),
'TeamMagmaBaltoyEXTeamMagmavsTeamAqua60.jpg' : require('../../../resources/images/cards/TeamMagmaBaltoyEXTeamMagmavsTeamAqua60.jpg'),
'TeamMagmaAggronEXTeamMagmavsTeamAqua7.jpg' : require('../../../resources/images/cards/TeamMagmaAggronEXTeamMagmavsTeamAqua7.jpg'),
'TeamMagmaPoochyenaEXTeamMagmavsTeamAqua65.jpg' : require('../../../resources/images/cards/TeamMagmaPoochyenaEXTeamMagmavsTeamAqua65.jpg'),
'TeamMagmaAronEXTeamMagmavsTeamAqua58.jpg' : require('../../../resources/images/cards/TeamMagmaAronEXTeamMagmavsTeamAqua58.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'TeamMagmaMightyenaEXTeamMagmavsTeamAqua37.jpg' : require('../../../resources/images/cards/TeamMagmaMightyenaEXTeamMagmavsTeamAqua37.jpg'),
'TeamMagmaLaironEXTeamMagmavsTeamAqua20.jpg' : require('../../../resources/images/cards/TeamMagmaLaironEXTeamMagmavsTeamAqua20.jpg'),
'TeamMagmaSchemerEXTeamMagmavsTeamAqua70.jpg' : require('../../../resources/images/cards/TeamMagmaSchemerEXTeamMagmavsTeamAqua70.jpg'),
'TeamMagmaClaydolEXTeamMagmavsTeamAqua33.jpg' : require('../../../resources/images/cards/TeamMagmaClaydolEXTeamMagmavsTeamAqua33.jpg'),
'TeamMagmaBeltEXTeamMagmavsTeamAqua81.jpg' : require('../../../resources/images/cards/TeamMagmaBeltEXTeamMagmavsTeamAqua81.jpg'),
'DoubleFullHealEXSandstorm86.jpg' : require('../../../resources/images/cards/DoubleFullHealEXSandstorm86.jpg'),
'TeamMagmaHoundourEXTeamMagmavsTeamAqua63.jpg' : require('../../../resources/images/cards/TeamMagmaHoundourEXTeamMagmavsTeamAqua63.jpg'),
'TeamMagmaHoundourEXTeamMagmavsTeamAqua62.jpg' : require('../../../resources/images/cards/TeamMagmaHoundourEXTeamMagmavsTeamAqua62.jpg'),
'FireEnergyExpedition161.jpg' : require('../../../resources/images/cards/FireEnergyExpedition161.jpg')};

export default MagmaHalfDeck1