const MagmaHalfDeck2 =
 {'TeamMagmaHideoutEXTeamMagmavsTeamAqua83.jpg' : require('../../../resources/images/cards/TeamMagmaHideoutEXTeamMagmavsTeamAqua83.jpg'),
'MagmaEnergyEXTeamMagmavsTeamAqua87.jpg' : require('../../../resources/images/cards/MagmaEnergyEXTeamMagmavsTeamAqua87.jpg'),
'TeamMagmaRhydonEXTeamMagmavsTeamAqua22.jpg' : require('../../../resources/images/cards/TeamMagmaRhydonEXTeamMagmavsTeamAqua22.jpg'),
'TeamMagmaAronEXTeamMagmavsTeamAqua59.jpg' : require('../../../resources/images/cards/TeamMagmaAronEXTeamMagmavsTeamAqua59.jpg'),
'MaxieEXTeamMagmavsTeamAqua73.jpg' : require('../../../resources/images/cards/MaxieEXTeamMagmavsTeamAqua73.jpg'),
'TeamMagmaBallEXTeamMagmavsTeamAqua80.jpg' : require('../../../resources/images/cards/TeamMagmaBallEXTeamMagmavsTeamAqua80.jpg'),
'TeamMagmaConspiratorEXTeamMagmavsTeamAqua82.jpg' : require('../../../resources/images/cards/TeamMagmaConspiratorEXTeamMagmavsTeamAqua82.jpg'),
'FightingEnergyEXRubySapphire105.jpg' : require('../../../resources/images/cards/FightingEnergyEXRubySapphire105.jpg'),
'TeamMagmaLaironEXTeamMagmavsTeamAqua36.jpg' : require('../../../resources/images/cards/TeamMagmaLaironEXTeamMagmavsTeamAqua36.jpg'),
'TeamMagmaAggronEXTeamMagmavsTeamAqua7.jpg' : require('../../../resources/images/cards/TeamMagmaAggronEXTeamMagmavsTeamAqua7.jpg'),
'TeamMagmaNumelEXTeamMagmavsTeamAqua64.jpg' : require('../../../resources/images/cards/TeamMagmaNumelEXTeamMagmavsTeamAqua64.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'TeamMagmaMightyenaEXTeamMagmavsTeamAqua21.jpg' : require('../../../resources/images/cards/TeamMagmaMightyenaEXTeamMagmavsTeamAqua21.jpg'),
'TeamMagmaSchemerEXTeamMagmavsTeamAqua70.jpg' : require('../../../resources/images/cards/TeamMagmaSchemerEXTeamMagmavsTeamAqua70.jpg'),
'TeamMagmaCameruptEXTeamMagmavsTeamAqua19.jpg' : require('../../../resources/images/cards/TeamMagmaCameruptEXTeamMagmavsTeamAqua19.jpg'),
'TeamMagmaRhyhornEXTeamMagmavsTeamAqua67.jpg' : require('../../../resources/images/cards/TeamMagmaRhyhornEXTeamMagmavsTeamAqua67.jpg'),
'TeamMagmaPoochyenaEXTeamMagmavsTeamAqua66.jpg' : require('../../../resources/images/cards/TeamMagmaPoochyenaEXTeamMagmavsTeamAqua66.jpg'),
'TeamMagmaGroudonEXTeamMagmavsTeamAqua9.jpg' : require('../../../resources/images/cards/TeamMagmaGroudonEXTeamMagmavsTeamAqua9.jpg'),
'FireEnergyExpedition161.jpg' : require('../../../resources/images/cards/FireEnergyExpedition161.jpg'),
'TeamMagmaRhyhornEXTeamMagmavsTeamAqua68.jpg' : require('../../../resources/images/cards/TeamMagmaRhyhornEXTeamMagmavsTeamAqua68.jpg')};

export default MagmaHalfDeck2