const OceansKyogreexConstructedStarterDeck =
 {'TorchicEXCrystalGuardians65.jpg' : require('../../../resources/images/cards/TorchicEXCrystalGuardians65.jpg'),
'BillMaintenanceExpedition137.jpg' : require('../../../resources/images/cards/BillMaintenanceExpedition137.jpg'),
'GrovyleEXCrystalGuardians19.jpg' : require('../../../resources/images/cards/GrovyleEXCrystalGuardians19.jpg'),
'SquirtleEXCrystalGuardians63.jpg' : require('../../../resources/images/cards/SquirtleEXCrystalGuardians63.jpg'),
'PokeNavEXRubySapphire88.jpg' : require('../../../resources/images/cards/PokeNavEXRubySapphire88.jpg'),
'WartortleEXCrystalGuardians42.jpg' : require('../../../resources/images/cards/WartortleEXCrystalGuardians42.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'PokeBallEXFireRedLeafGreen95.jpg' : require('../../../resources/images/cards/PokeBallEXFireRedLeafGreen95.jpg'),
'EnergySearchExpedition153.jpg' : require('../../../resources/images/cards/EnergySearchExpedition153.jpg'),
'WaterEnergyEXRubySapphire106.jpg' : require('../../../resources/images/cards/WaterEnergyEXRubySapphire106.jpg'),
'WarpPointEXUnseenForces93.jpg' : require('../../../resources/images/cards/WarpPointEXUnseenForces93.jpg'),
'CombuskenEXCrystalGuardians31.jpg' : require('../../../resources/images/cards/CombuskenEXCrystalGuardians31.jpg'),
'BlastoiseEXCrystalGuardians14.jpg' : require('../../../resources/images/cards/BlastoiseEXCrystalGuardians14.jpg'),
'CelioNetworkEXFireRedLeafGreen88.jpg' : require('../../../resources/images/cards/CelioNetworkEXFireRedLeafGreen88.jpg'),
'PsychicEnergyEXRubySapphire107.jpg' : require('../../../resources/images/cards/PsychicEnergyEXRubySapphire107.jpg'),
'MultiEnergyEXSandstorm93.jpg' : require('../../../resources/images/cards/MultiEnergyEXSandstorm93.jpg'),
'TreeckoEXCrystalGuardians68.jpg' : require('../../../resources/images/cards/TreeckoEXCrystalGuardians68.jpg'),
'FireEnergyExpedition161.jpg' : require('../../../resources/images/cards/FireEnergyExpedition161.jpg'),
'KyogreexEXCrystalGuardians95.jpg' : require('../../../resources/images/cards/KyogreexEXCrystalGuardians95.jpg')};

export default OceansKyogreexConstructedStarterDeck