const PremiumFile2 =
  {'neo-premium-file-2-001.jpg' : require('../../../resources/images/cards/neo-premium-file-2-001.jpg'),
'neo-premium-file-2-002.jpg' : require('../../../resources/images/cards/neo-premium-file-2-002.jpg'),
'neo-premium-file-2-003.jpg' : require('../../../resources/images/cards/neo-premium-file-2-003.jpg'),
'neo-premium-file-2-004.jpg' : require('../../../resources/images/cards/neo-premium-file-2-004.jpg'),
'neo-premium-file-2-005.jpg' : require('../../../resources/images/cards/neo-premium-file-2-005.jpg'),
'neo-premium-file-2-006.jpg' : require('../../../resources/images/cards/neo-premium-file-2-006.jpg'),
'neo-premium-file-2-007.jpg' : require('../../../resources/images/cards/neo-premium-file-2-007.jpg'),
'neo-premium-file-2-008.jpg' : require('../../../resources/images/cards/neo-premium-file-2-008.jpg'),
'neo-premium-file-2-009.jpg' : require('../../../resources/images/cards/neo-premium-file-2-009.jpg')};
export default PremiumFile2
