const PremiumFile3 =
  {'neo-premium-file-3-001.jpg' : require('../../../resources/images/cards/neo-premium-file-3-001.jpg'),
'neo-premium-file-3-002.jpg' : require('../../../resources/images/cards/neo-premium-file-3-002.jpg'),
'neo-premium-file-3-003.jpg' : require('../../../resources/images/cards/neo-premium-file-3-003.jpg'),
'neo-premium-file-3-004.jpg' : require('../../../resources/images/cards/neo-premium-file-3-004.jpg'),
'neo-premium-file-3-005.jpg' : require('../../../resources/images/cards/neo-premium-file-3-005.jpg'),
'neo-premium-file-3-006.jpg' : require('../../../resources/images/cards/neo-premium-file-3-006.jpg'),
'neo-premium-file-3-007.jpg' : require('../../../resources/images/cards/neo-premium-file-3-007.jpg'),
'neo-premium-file-3-008.jpg' : require('../../../resources/images/cards/neo-premium-file-3-008.jpg'),
'neo-premium-file-3-009.jpg' : require('../../../resources/images/cards/neo-premium-file-3-009.jpg')};
export default PremiumFile3
