const PremiumFile1 =
  {'CroconawNeoGenesis32.jpg' : require('../../../resources/images/cards/CroconawNeoGenesis32.jpg'),
'BayleefNeoGenesis28.jpg' : require('../../../resources/images/cards/BayleefNeoGenesis28.jpg'),
'TotodileNeoGenesis80.jpg' : require('../../../resources/images/cards/TotodileNeoGenesis80.jpg'),
'FeraligatrNeoGenesis5.jpg' : require('../../../resources/images/cards/FeraligatrNeoGenesis5.jpg'),
'MeganiumNeoGenesis10.jpg' : require('../../../resources/images/cards/MeganiumNeoGenesis10.jpg'),
'CyndaquilNeoGenesis56.jpg' : require('../../../resources/images/cards/CyndaquilNeoGenesis56.jpg'),
'QuilavaNeoGenesis46.jpg' : require('../../../resources/images/cards/QuilavaNeoGenesis46.jpg'),
'ChikoritaNeoGenesis54.jpg' : require('../../../resources/images/cards/ChikoritaNeoGenesis54.jpg'),
'TyphlosionNeoGenesis18.jpg' : require('../../../resources/images/cards/TyphlosionNeoGenesis18.jpg')};
export default PremiumFile1
