const PremiumFile1 =
  {'neo-premium-file-001.jpg' : require('../../../resources/images/cards/neo-premium-file-001.jpg'),
'neo-premium-file-002.jpg' : require('../../../resources/images/cards/neo-premium-file-002.jpg'),
'neo-premium-file-003.jpg' : require('../../../resources/images/cards/neo-premium-file-003.jpg'),
'neo-premium-file-004.jpg' : require('../../../resources/images/cards/neo-premium-file-004.jpg'),
'neo-premium-file-005.jpg' : require('../../../resources/images/cards/neo-premium-file-005.jpg'),
'neo-premium-file-006.jpg' : require('../../../resources/images/cards/neo-premium-file-006.jpg'),
'neo-premium-file-007.jpg' : require('../../../resources/images/cards/neo-premium-file-007.jpg'),
'neo-premium-file-008.jpg' : require('../../../resources/images/cards/neo-premium-file-008.jpg'),
'neo-premium-file-009.jpg' : require('../../../resources/images/cards/neo-premium-file-009.jpg')};
export default PremiumFile1
