const RainbowIsland =
  {'LedybaSouthernIslands7.jpg' : require('../../../resources/images/cards/LedybaSouthernIslands7.jpg'),
'MewSouthernIslands1.jpg' : require('../../../resources/images/cards/MewSouthernIslands1.jpg'),
'IvysaurSouthernIslands5.jpg' : require('../../../resources/images/cards/IvysaurSouthernIslands5.jpg'),
'OnixSouthernIslands3.jpg' : require('../../../resources/images/cards/OnixSouthernIslands3.jpg'),
'PidgeotSouthernIslands2.jpg' : require('../../../resources/images/cards/PidgeotSouthernIslands2.jpg'),
'ButterfreeSouthernIslands9.jpg' : require('../../../resources/images/cards/ButterfreeSouthernIslands9.jpg'),
'TogepiSouthernIslands4.jpg' : require('../../../resources/images/cards/TogepiSouthernIslands4.jpg'),
'RaticateSouthernIslands6.jpg' : require('../../../resources/images/cards/RaticateSouthernIslands6.jpg'),
'JigglypuffSouthernIslands8.jpg' : require('../../../resources/images/cards/JigglypuffSouthernIslands8.jpg')};
export default RainbowIsland
