const RainbowIsland =
  {'islands-2-001.jpg' : require('../../../resources/images/cards/islands-2-001.jpg'),
'islands-2-002.jpg' : require('../../../resources/images/cards/islands-2-002.jpg'),
'islands-2-003.jpg' : require('../../../resources/images/cards/islands-2-003.jpg'),
'islands-2-004.jpg' : require('../../../resources/images/cards/islands-2-004.jpg'),
'islands-2-005.jpg' : require('../../../resources/images/cards/islands-2-005.jpg'),
'islands-2-006.jpg' : require('../../../resources/images/cards/islands-2-006.jpg'),
'islands-2-007.jpg' : require('../../../resources/images/cards/islands-2-007.jpg'),
'islands-2-008.jpg' : require('../../../resources/images/cards/islands-2-008.jpg'),
'islands-2-009.jpg' : require('../../../resources/images/cards/islands-2-009.jpg')};
export default RainbowIsland
