const RayquazaConstructedStarterDeck =
 {'SwitchEXRubySapphire92.jpg' : require('../../../resources/images/cards/SwitchEXRubySapphire92.jpg'),
'RayquazaexEXDeoxys102.jpg' : require('../../../resources/images/cards/RayquazaexEXDeoxys102.jpg'),
'EnergyChargeNeoGenesis85.jpg' : require('../../../resources/images/cards/EnergyChargeNeoGenesis85.jpg'),
'SlugmaEXDeoxys74.jpg' : require('../../../resources/images/cards/SlugmaEXDeoxys74.jpg'),
'LombreEXDeoxys34.jpg' : require('../../../resources/images/cards/LombreEXDeoxys34.jpg'),
'ProfessorCozmoDiscoveryEXDeoxys90.jpg' : require('../../../resources/images/cards/ProfessorCozmoDiscoveryEXDeoxys90.jpg'),
'MasterBallGymChallenge116.jpg' : require('../../../resources/images/cards/MasterBallGymChallenge116.jpg'),
'LotadEXDeoxys63.jpg' : require('../../../resources/images/cards/LotadEXDeoxys63.jpg'),
'PotionSecretWonders127.jpg' : require('../../../resources/images/cards/PotionSecretWonders127.jpg'),
'MagcargoEXDeoxys37.jpg' : require('../../../resources/images/cards/MagcargoEXDeoxys37.jpg'),
'LadyOutingEXRubySapphire83.jpg' : require('../../../resources/images/cards/LadyOutingEXRubySapphire83.jpg'),
'WaterEnergyEXRubySapphire106.jpg' : require('../../../resources/images/cards/WaterEnergyEXRubySapphire106.jpg'),
'LudicoloEXDeoxys19.jpg' : require('../../../resources/images/cards/LudicoloEXDeoxys19.jpg'),
'ElectrikeEXDeoxys59.jpg' : require('../../../resources/images/cards/ElectrikeEXDeoxys59.jpg'),
'LightningEnergyEXRubySapphire109.jpg' : require('../../../resources/images/cards/LightningEnergyEXRubySapphire109.jpg'),
'BalloonBerryEXDeoxys84.jpg' : require('../../../resources/images/cards/BalloonBerryEXDeoxys84.jpg'),
'ManectricEXDeoxys38.jpg' : require('../../../resources/images/cards/ManectricEXDeoxys38.jpg'),
'MultiEnergyEXSandstorm93.jpg' : require('../../../resources/images/cards/MultiEnergyEXSandstorm93.jpg'),
'FireEnergyExpedition161.jpg' : require('../../../resources/images/cards/FireEnergyExpedition161.jpg')};

export default RayquazaConstructedStarterDeck