const TropicalIsland =
  {'LaprasSouthernIslands12.jpg' : require('../../../resources/images/cards/LaprasSouthernIslands12.jpg'),
'ExeggutorSouthernIslands13.jpg' : require('../../../resources/images/cards/ExeggutorSouthernIslands13.jpg'),
'LickitungSouthernIslands16.jpg' : require('../../../resources/images/cards/LickitungSouthernIslands16.jpg'),
'WartortleSouthernIslands15.jpg' : require('../../../resources/images/cards/WartortleSouthernIslands15.jpg'),
'TentacruelSouthernIslands10.jpg' : require('../../../resources/images/cards/TentacruelSouthernIslands10.jpg'),
'VileplumeSouthernIslands17.jpg' : require('../../../resources/images/cards/VileplumeSouthernIslands17.jpg'),
'PrimeapeSouthernIslands.jpg' : require('../../../resources/images/cards/PrimeapeSouthernIslands.jpg'),
'SlowkingSouthernIslands14.jpg' : require('../../../resources/images/cards/SlowkingSouthernIslands14.jpg'),
'MarillSouthernIslands11.jpg' : require('../../../resources/images/cards/MarillSouthernIslands11.jpg')};
export default TropicalIsland
