const TropicalIsland =
  {'islands-001.jpg' : require('../../../resources/images/cards/islands-001.jpg'),
'islands-002.jpg' : require('../../../resources/images/cards/islands-002.jpg'),
'islands-003.jpg' : require('../../../resources/images/cards/islands-003.jpg'),
'islands-004.jpg' : require('../../../resources/images/cards/islands-004.jpg'),
'islands-005.jpg' : require('../../../resources/images/cards/islands-005.jpg'),
'islands-006.jpg' : require('../../../resources/images/cards/islands-006.jpg'),
'islands-007.jpg' : require('../../../resources/images/cards/islands-007.jpg'),
'islands-008.jpg' : require('../../../resources/images/cards/islands-008.jpg'),
'islands-009.jpg' : require('../../../resources/images/cards/islands-009.jpg')};
export default TropicalIsland
